### ISSUE TITLE
Consider contributing the palette to https://github.com/dracula/dracula-theme

### ISSUE THREAD

**Issue by jonasws** [dracula/vimium#1]
Awesome job of creating this palette!

It is however, not as easy to find as it should! It would be awesome if this becomes part of the [dracula "hub"](https://github.com/dracula/dracula-theme).

**Comment by Trollwut** [comment]
Indeed it is currently under progress of being integrated! => https://github.com/dracula/steam

Unfortunately, since the last two releases, this skin might have some inconsistencies, so I wouldn't include it in the official "hub" until this has been fixed.

Thanks for your compliment! I simply used the Dracula colors :>

**Comment by jonasws** [comment]
The link you posted points to the Steam integration. I suggested the VIMIUM css to be contributed, but they may be related in some way?

**Comment by Trollwut** [comment]
whoopsie, my fault. Did some work on the Steam one and got this mail. Next time I should check which project I'm in :D

well nope, vimium is not yet considered for the "hub". I might do that on time!

**Comment by Trollwut** [comment]
Made an issue for it in the official Dracula-theme repo: https://github.com/dracula/dracula-theme/issues/347

**Comment by Trollwut** [comment]
yo @jonasws, guess what just happened 😎

as you can see, we're now in the Dracula repo. I just wait for the last confirmation that everything went right and will then close this issue :)

**Comment by Trollwut** [comment]
And the migration has happened. This repo is now officially in the hub!

Reference ticket: https://github.com/dracula/dracula-theme/issues/347

Thanks @jonasws for recommending this step!
