### ISSUE TITLE
Access to vimium-dracula.css on website

### ISSUE THREAD

**Issue by Lubieerror** [dracula/vimium#10]
Please update content of https://draculatheme.com/vimium because for now only extensions links are available.
You have to open theme git repo to access the file:

Now:
![image](https://user-images.githubusercontent.com/11427815/132961706-8b28104d-2fdc-47ab-a6ad-8885628bfe46.png)

Expected (something like this):
![image](https://user-images.githubusercontent.com/11427815/132961774-8508e4b2-a13c-4fc5-bd6e-b91c2811b695.png)

**Comment by Trollwut** [comment]
That's indeed a good improvement!

See this pull request: https://github.com/dracula/vimium/pull/11

I clearified the "Install" part and added a link to the mentioned CSS file. I did not add the file also to the Install section, as the link would be redundant and people might ask if there is a difference in these two links.

**Comment by Lubieerror** [comment]
Thanks ❤
