### ISSUE TITLE
White placeholder when active vimium command in a dark background page

### ISSUE THREAD

**Issue by Aiee** [dracula/vimium#6]
![Screen Shot 2021-04-21 at 2 23 40 PM](https://user-images.githubusercontent.com/18348405/115506198-2e9cc500-a2ad-11eb-949b-a8dbf7547653.png)

As shown in the screenshot. When using commands such as 
```
o       Open URL, bookmark, or history entry
O       Open URL, bookmark, history entry in a new tab
b       Open bookmark
B       Open bookmark in a new tab
```

in a dark background, there seems to be a white placeholder with it. It would be nice if the color can be consistent with the dark color.

**Comment by Trollwut** [comment]
Can't reproduce:

![](https://i.imgur.com/fYqHJXY.png)

AFAIK you use the "dark" theme of GitHub itself. I used the "dim" variant and also tested with the "dark" one, too.

**Can you give me some more information on how to reproduce?**

Maybe some other browser addon plays around with color.

**Comment by Aiee** [comment]
Hi Trollwut, 
Thanks for your reply. I also tested with both "dark" and "dim" Github themes and the problem persisted.

And this problem seems only take place on Github, as the theme works well with youtube's dark theme and other websites with dark backgrounds. Besides that, I don't think any other extension I installed has an impact on the browser's appearance.

For your reference, I'm using Chrome (Version 90.0.4430.85 (Official Build) (x86_64)) on macOS Big Sur 11.2.3

**Comment by Trollwut** [comment]
Hey indeed! No problem in Firefox.

But I opened Chromium and installed the extension, loaded the Custom CSS. On bright GitHub, everythings ok (no white box).

On Dark settings, yes, I can reproduce your problem. Unfortunately, I'm no Chrom(ium) user at all, so someone else might have better insights on why this appears.

**Comment by touhidulshawan** [comment]
@Trollwut Can you check this #8 pull request

**Comment by touhidulshawan** [comment]
white background is appearing only on github page not in other web pages

**Comment by Trollwut** [comment]
answered to your pull request :)

https://github.com/dracula/vimium/pull/8

**Comment by touhidulshawan** [comment]
@Aiee  Check this more information: 
https://github.com/philc/vimium/issues/3732#issuecomment-749997600

I try to change the iframe background color through CSS but it does not select that element through this vimium-dracula.css. Chrome or chrome-based browser `color-scheme: dark,` used by Github Dark mode, will cause the transparent area to white. Now we have to wait for the next update of vimium or you can modify or build from the source.

**Comment by Aiee** [comment]
> @Aiee Check this more information:
> [philc/vimium#3732 (comment)](https://github.com/philc/vimium/issues/3732#issuecomment-749997600)
> 
> I try to change the iframe background color through CSS but it does not select that element through this vimium-dracula.css. Chrome or chrome-based browser `color-scheme: dark,` used by Github Dark mode, will cause the transparent area to white. Now we have to wait for the next update of vimium or you can modify or build from the source.

Hi, thanks for the explanation. I'll probably wait for the next release.

Please feel free to close this issue.
